### PR TITLE
Resource match Api Support

### PR DESCRIPTION
**Pull request by vipinvkmenon**
This pull requests support for Resource Match Api

### CODE REVIEW

**Comment by vipinvkmenon** [comment]
Hi...May I close this if not needed?

**Comment by sneal** [comment]
@vipinvkmenon This seems like a reasonable addition, do you mind updating the PR to resolve the merge conflicts?

**Comment by vipinvkmenon** [comment]
Good to hear this, sure will have a look.

**Comment by vipinvkmenon** [comment]
Updated the PR and resolved the conflicts.
@sneal

**Comment by sneal** [comment]
Thanks for the PR!

**Pull request merged**
