### PR TITLE
Added another date format for AppStats.Usage.Time and Bugfix for app.crash event types

### PR DESCRIPTION
**Pull request by dave-malone**
While testing against the /v2/apps/{guid}/stats api, I discovered that yet another time format is returned from the API for the stats.usage.time field. The date returned was `2017-04-12 15:27:44 UTC`, and to support this date, the date format of `2006-01-02 15:04:05 MST` was added to the list of possible formats used to try to evaluate the usage.time values that are returned in this payload.

Another scenario that was encountered while testing was that not all events returned from the /v2/events api contain an entity.metadata.request block. In particular, the fields for `app.crash` event types will be returned within the entity.metadata block. The current struct mappings will swallow these values, and clients will not be able to consume the ExitDetails and ExitReason values returned from that api call. Those fields have been moved up to the MetaData nested struct.

### CODE REVIEW

**Comment by dave-malone** [comment]
Testing again against a live endpoint just to be certain

**Comment by dave-malone** [comment]
Tested against a live api (PWS) with a client that I've been building

**Comment by lnguyen** [comment]
@dave-malone can you fix travis?

**Comment by dave-malone** [comment]
Travis was passing before I closed the PR. Unsure as to why it's failing now. 

https://travis-ci.org/cloudfoundry-community/go-cfclient/builds/221463033

**Pull request merged**
