### PR TITLE
add function to get details of service key using guid

### PR DESCRIPTION
**Pull request by amitgurav04**
I have added function GetServiceKeyByGuid in service_keys.go

It takes service_key guid as an input and return the service_key json as an output.

Please let me know if any modification required.

### CODE REVIEW

**Comment by lnguyen** [comment]
Can you add some tests?

**Comment by amitgurav04** [comment]
OK. I will add.

**Comment by drnic** [comment]
@amitgurav04 how are you feeling about writing a test for this old PR? today looks like a fabulous test writing day?

**Comment by sneal** [comment]
I rebased this and added a test, merged.

**Pull request closed without merging**
