### PR TITLE
Service instance update request

### PR DESCRIPTION
**Pull request by elgohr**
Introduce struct for simpler usage

### CODE REVIEW

**Comment by jghiloni** [comment]
I like the idea of this PR, but it would be a breaking change. Can you think of any ways to introduce this in such a way that it wouldn't break anything?

**Comment by elgohr** [comment]
We could have both, but this would be more code to maintain. Furthermore this method is an exception in terms of behavior (other methods already use custom structs as attributes). In this way I would vote for breaking.

**Comment by elgohr** [comment]
This fix was introduced less than a week after the initial introduction of the method.
The longer this layes around, the more people will break...

**Comment by mxplusb** [comment]
> it would be a breaking change

What's wrong with a breaking change so long as there's a version bump?

**Comment by elgohr** [comment]
Ping

**Comment by mxplusb** [comment]
@jghiloni *poke*

**Comment by sneal** [comment]
If we can make this a backwards compatible change I'll merge it.

**Comment by sneal** [comment]
service instance update support added in v3 branch

**Pull request closed without merging**
