### PR TITLE
Fix ASG ICMP Bug

### PR DESCRIPTION
**Pull request by johnlonganecker**
This will fix the Issue #68 I submitted.

I removed the omitempty on `Code` and `Type` and programmatically remove if it is not the `icmp` protocol.

Perhaps there is a cleaner fix, but this at least allows us to create/update security groups with the ICMP protocol

### CODE REVIEW

**Comment by shinji62** [comment]
`Code` and `Type` are optional so I think the `omitempty` make sense here ...

Checking I would like prefer to see a check in a code that in the struct which respect the api definition.

What do you think @lnguyen  ?

**Comment by johnlonganecker** [comment]
When I was running this if the protocol was not icmp and `Type` and `Code` were set to 0 it would fail. So that is why I had to remove them.

**Comment by johnlonganecker** [comment]
Actually now I remember what the problem was. It has been awhile since I thought about it.

If `Code` and `Type` were set to `0` `omitempty` would consider that a zero value and then omit it which is not what you would want. Perhaps we can change those fields to pointers to get around this problem.

If `Code` and `Type` were left in for the other protocols (besides ICMP) that would cause an error.

**Comment by lnguyen** [comment]
@johnlonganecker can you rebase

**Comment by shinji62** [comment]
@johnlonganecker I guess cleaner fix may exist too but I didn't take a look. 
So I will let @lnguyen decide if ok to merge or not.

**Comment by lnguyen** [comment]
Just need some tests and rebase with master

**Comment by johnlonganecker** [comment]
I should have time today to take a look.

**Pull request merged**
